name: Deploy test with scheduled and manual trigger
on:
  # schedule:
  #   - cron: '* * * * *'
  workflow_dispatch: 
jobs:
  should_run:
    runs-on: ubuntu-latest
    name: Check if deploy should run
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: Check commits within last 24 hours
        id: should_run
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: test $(git log --since="24 hours ago" --format=oneline -i -- deploy | wc -l) -eq 1 && echo "::set-output name=should_run::false"
  deploy:
    needs: should_run
    if: ${{ needs.should_run.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Deploy Terraform changes
    steps:
      - name: Echo test message
        run: echo "Deploying Terraform changes"