name: Deploy test with scheduled and manual trigger
on:
  schedule:
     - cron: '0 03 * * *'
  workflow_dispatch: 
jobs:
  should_run:
    runs-on: ubuntu-latest
    name: Check if deploy should run
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: Check commits within last 24 hours
        if: ${{ github.event_name == 'schedule' }}
        id: should_run
        run: test $(git log --since="24 hours ago" --format=oneline -i -- deploy | wc -l) -eq 0 && echo "::set-output name=should_run::false" || echo "::set-output name=should_run::true"
  deploy:
    needs: should_run
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    name: Deploy Terraform changes
    steps:
      - name: Echo test message
        run: |
          echo "Deploying Terraform changes"
          echo ${{ needs.should_run.outputs.should_run }}
