name: Deploy test with scheduled and manual trigger
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 
jobs:
  should_run:
    runs-on: ubuntu-latest
    name: Check if deploy should run
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - name: Check commits within last 24 hours
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'schedule' }}
        run: test $(git log main --after="24 hours" --format=oneline -i -- deploy | wc -l) -eq 0 && echo "::set-output name=should_run::false"
  deploy:
    needs: should_run
    if: ${{ needs.should_run.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Deploy Terraform changes
    steps:
      - name: Echo test message
        run: echo "Deploying Terraform changes"